call plug#begin()

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'morhetz/gruvbox'
Plug 'scrooloose/nerdTree'
Plug 'tpope/vim-fugitive'

call plug#end()

let g:airline_powerline_fonts = 1
let g:airline_theme='base16_gruvbox_dark_hard'

colorscheme gruvbox

set rnu
set list

set shiftwidth=4
set tabstop=4
set expandtab

nmap <C-n> :NERDTreeToggle<CR>
